jobs:
  - job: linux
    pool:
      vmImage: "ubuntu-latest"
    strategy:
      matrix:
        Python37:
          python.version: "3.7"

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python.version)"
      - script: pip install tox
      - script: tox -e lint
      - script: tox -e ci
